version: '2'

services:
# -------------------------------------------
# ------------------ Sails ------------------
# -------------------------------------------
    # sails container
    sails:
        build: ./builds/sails
        volumes:
            - "./data/sails:/srv/sails"
        ports:
            - "1337:1337"
        links:
            - "mongodb:mongodb"

# ----------------------------------------------
# ------------------ Database ------------------
# ----------------------------------------------
    # Mongodb
    mongodb:
        image: mongo:latest
        restart: always
        volumes:
            - "mongoVolume:/data/db"
        ports:
            - "27017:27017"
        command: --smallfiles --auth

volumes:
  mongoVolume:
      driver: local
