version: '2'

services:
# -------------------------------------------
# ------------------ Sails ------------------
# -------------------------------------------
    # sails container
    sails:
        build: ./builds/sails
        volumes:
            - "./data/sails:/srv/sails"
        ports:
            - "1337:1337"
        links:
            - "mysqldb:mysqldb"

# ----------------------------------------------
# ------------------ Database ------------------
# ----------------------------------------------
    # Mysql
    mysqldb:
        image: 'mysql/mysql-server:latest'
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: 'Packebian'
            MYSQL_USER: 'packebian'
            MYSQL_PASSWORD: 'packebian123'
            MYSQL_ROOT_PASSWORD: 'mysqldb123'
        volumes:
            - mysqlVolume:/var/lib/mysql
            - ./init/mysql/:/docker-entrypoint-initdb.d/
volumes:
  mysqlVolume:
      driver: local
